### PR TITLE
I have no idea...

### PR DESCRIPTION
**Pull request by Bobbbay**
The index.html and icon.xsvg aren't in the master after merging #7... Let's try again, I guess...

I wonder what in the world caused this !?!?

Thanks, Bobbbay

### CODE REVIEW

**Comment by iinc0gnit0** [comment]
I just fixed it now

**Comment by Bobbbay** [comment]
Screenshot_20200204-172726
I don't understand anymore. It's still not there! I waited a couple days to see if maybe my devices and/or GitHub was acting up, but as you can see, those 2 files don't exist...

Bobbbay

**Comment by Bobbbay** [comment]
@iinc0gnit0 I still don't see it... Has there been any development in the situation?

**Comment by iinc0gnit0** [comment]
Yes, we are working on it right now. It should be out soon.

**Pull request closed without merging**
